apiVersion: v1
kind: Service
metadata:
  name: longhorn-frontend-service
spec:
  namespace: longhorn-system
  type: NodePort
  selector:
    app: longhorn-ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30001
