version: '3.8'

# Basic Home Assistant setup
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    tty: true
    restart: unless-stopped
    privileged: true
    network_mode: host
    depends_on:
      - mariadb
      - zigbee2mqtt
    environment:
      - VIRTUAL_HOST=${HA_DOMAIN}
      - VIRTUAL_PORT=${HA_PORT}
      - LETSENCRYPT_HOST=${HA_DOMAIN}
      - TZ=${TZ}
    volumes:
      - ./hassio:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${HA_PORT}:${HA_PORT}
    devices:
      - ${HA_RF_DEVICE}:/dev/ttyACM0

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: unless-stopped
    depends_on:
      - mqtt
    environment:
      - VIRTUAL_HOST=${Z2M_DOMAIN}
      - VIRTUAL_PORT=${Z2M_PORT}
      - LETSENCRYPT_HOST=${Z2M_DOMAIN}
      - TZ=${TZ}
    ports:
      - ${Z2M_PORT}:${Z2M_PORT}
    volumes:
      - ./zigbee2mqtt:/app/data
    devices:
      - ${Z2M_DEVICE}:/dev/ttyACM0

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: unless-stopped
    ports:
      - ${MQTT_PORT}:${MQTT_PORT}
      - ${MQTT_WEBSOCKET_PORT}:${MQTT_WEBSOCKET_PORT}
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log

  vscode:
    image: codercom/code-server:latest
    container_name: vscode
    restart: unless-stopped
    user: ${VSCODE_USER}:${VSCODE_USER}
    depends_on:
      - homeassistant
      - zigbee2mqtt
      - mqtt
    environment:
      - VIRTUAL_HOST=${VSCODE_DOMAIN}
      - VIRTUAL_PORT=${VSCODE_PORT}
      - LETSENCRYPT_HOST=${VSCODE_DOMAIN}
      - PASSWORD=${VSCODE_PASSWORD}
      - DOCKER_USER=${VSCODE_USER}
    volumes:
      - ./hassio:/home/coder/project/hassio
      - ./mqtt:/home/coder/project/mqtt
      - ./zigbee2mqtt/data:/home/coder/project/zigbee2mqtt
      - ./vscode/.config:/home/coder/.config
      - ./vscode:/home/coder/project
    ports:
      - ${VSCODE_PORT}:${VSCODE_PORT}

  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - ${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}
      - ${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}
    volumes:
      - ./nginx-proxy/htpasswd:/etc/nginx/htpasswd
      - ./nginx-proxy/conf:/etc/nginx/conf.d
      - ./nginx-proxy/certs:/etc/nginx/certs
      - ./nginx-proxy/vhost:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  nginx-proxy-acme:
    container_name: nginx-proxy-acme
    image: nginxproxy/acme-companion
    restart: unless-stopped
    environment:
      - DEFAULT_EMAIL=${SSL_EMAIL}
    volumes:
      - ./nginx-proxy/certs:/etc/nginx/certs
      - ./nginx-proxy/vhost:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx-proxy-acme/acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
