apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vscode
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vscode
    spec:
      containers:
        - name: vscode
          image: codercom/code-server:latest
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          env:
            - name: PASSWORD
              value: "SeCrEtP@s5"
            - name: DOCKER_USER
              value: "root"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: vscode-config-storage
              mountPath: /home/coder/.config
            - name: vscode-storage
              mountPath: /home/coder/project
            # - name: wordpress-storage
            #   mountPath: /home/coder/project/wordpress
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
      volumes:
        - name: vscode-config-storage
          persistentVolumeClaim:
            claimName: vscode-config-pvc
        - name: vscode-storage
          persistentVolumeClaim:
            claimName: vscode-pvc
        # - name: wordpress-storage
        #   persistentVolumeClaim:
        #     claimName: wordpress-pvc
