apiVersion: v1
kind: ConfigMap
metadata:
    name: mosquitto-config
data:
    mosquitto.conf: |
        allow_anonymous true
        listener 1883
        persistence false
        log_dest stdout
        log_timestamp true
        log_type error
        log_type warning
        log_type information
        log_type notice
        connection punter-bridge
        address 192.168.100.32:1883
        topic # out 0
