apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
spec:
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-nodeport
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1880
      nodePort: 30883
