apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
data:
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    homeassistant:
      name: Punter 3
      latitude: 52.021980
      longitude: 5.536150
      elevation: 3
      unit_system: metric
      currency: EUR
      country: NL
      external_url: "https://testha.punter3.nl"
      internal_url: "http://192.168.100.220:8123"
      time_zone: "Europe/Amsterdam"
      legacy_templates: false
      # customize: !include customize.yaml

    http:
      server_port: 8123
      use_x_forwarded_for: true
      trusted_proxies:
        - 172.0.0.0/8
        - 127.0.0.1
        - 10.244.0.0/16
        - ::1
        - 192.168.100.200/29

    tts:
      - platform: google_translate

    # automation: !include automations.yaml
    # script: !include scripts.yaml
    # scene: !include scenes.yaml
