apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:stable
          volumeMounts:
            - name: home-assistant-storage
              mountPath: /config
            - name: config-volume
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
            - name: tz-volume
              mountPath: /etc/localtime
              readOnly: true
          ports:
            - containerPort: 8123
          env:
            - name: TZ
              value: Europe/Amsterdam
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
      volumes:
        - name: config-volume
          configMap:
            name: home-assistant-config
        - name: tz-volume
          hostPath:
            path: /etc/localtime
        - name: home-assistant-storage
          persistentVolumeClaim:
            claimName: home-assistant-lh-pvc
