apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: lan-network
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "lan-network",
    "type": "macvlan",
    "master": "eth0",
    "mode": "bridge",
    "ipam": {
    "type": "host-local",
    "subnet": "192.168.100.0/24",
    "rangeStart": "192.168.100.231",
    "rangeEnd": "192.168.100.240",
    "routes": [
    { "dst": "0.0.0.0/0" }
    ],
    "gateway": "192.168.100.1"
    }
    }'
