apiVersion: apps/v1
kind: Deployment
metadata:
  name: miflora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miflora
  template:
    metadata:
      labels:
        app: miflora
    spec:
      imagePullSecrets:
        - name: docker-hub-secret
      containers:
        - name: miflora
          image: isenne/miflora-mqtt-daemon:latest
          imagePullPolicy: "Always"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config-volume
              mountPath: /config
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      volumes:
        - name: config-volume
          configMap:
            name: miflora-config
