apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    # Redirect www naar niet-www over HTTPS
    www.3904zz.nl, www.3904zz.nl:30080 {
        redir https://3904zz.nl{uri}
    }

    # Hoofddomein
    3904zz.nl, 3904zz.nl:30080 {
        reverse_proxy wordpress-service:80
    }
