apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    # Redirect www naar niet-www over HTTPS
    www.3904zz.nl {
        redir https://3904zz.nl{uri}
    }

    # Hoofddomein
    3904zz.nl {
        reverse_proxy wordpress-service:80
    }

    # Omleiden van zowel HTTP- als HTTPS-verkeer voor punter3.nl en subdomeinen
    punter3.nl, *.punter3.nl {
        @http {
            protocol http
        }

        @https {
            protocol https
        }

        # Voor HTTP-verkeer
        handle @http {
            reverse_proxy 192.168.100.32:80
        }

        # Voor HTTPS-verkeer
        handle @https {
            reverse_proxy 192.168.100.32:443
        }
    }
