apiVersion: v1
kind: ConfigMap
metadata:
    name: caddy-config
data:
    Caddyfile: |
        {
            email isenne@outlook.com
        }

        # Redirect www naar niet-www over HTTPS
        www.isenne.dev {
            redir https://isenne.dev{uri}
        }

        # Hoofddomein
        isenne.dev {
            reverse_proxy wordpress-service:80
        }

        ha.punter3.nl {
            reverse_proxy 192.168.100.32:8123
        }

        nr.punter3.nl {
            reverse_proxy 192.168.100.32:1880
        }

        longhorn.punter3.nl {
            @ipwhitelist {
                remote_ip 192.168.100.0/24 85.146.7.102
            }

            @vdvalkveenendaal {
                remote_ip 92.66.50.27
            }

            handle @ipwhitelist {
                reverse_proxy longhorn-frontend.longhorn-system.svc.cluster.local:80
            }

            handle vdvalkveenendaal {
                reverse_proxy longhorn-frontend.longhorn-system.svc.cluster.local:80
            }

            handle {
                respond "Hello, world!"
            }
        }
