apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    192.168.100.68:30080 {
        reverse_proxy wordpress-service:80
    }

    # Redirect www naar niet-www over HTTPS
    www.3904zz.nl:30080 {
        redir http://3904zz.nl:30080{uri}
    }

    # Hoofddomein
    3904zz.nl:30080 {
        reverse_proxy wordpress-service:80
    }
