apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    # Redirect www naar niet-www over HTTPS
    www.3904zz.nl {
        redir https://3904zz.nl{uri}
    }

    # Hoofddomein
    3904zz.nl {
        reverse_proxy wordpress-service:80
    }

    ha.punter3.nl {
        reverse_proxy 192.168.100.32:8123
    }

    z2m.punter3.nl {
        reverse_proxy 192.168.100.32:8099
    }

    code.punter3.nl {
        reverse_proxy 192.168.100.32:8081
    }

    nr.punter3.nl {
        reverse_proxy 192.168.100.32:1880
    }
