apiVersion: v1
kind: PersistentVolume
metadata:
  name: caddy-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.100.201
    path: /mnt/data/proxy
