apiVersion: v1
kind: Service
metadata:
  name: caddy-service
spec:
  type: NodePort
  selector:
    app: caddy
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 443
      nodePort: 30443
