apiVersion: v1
kind: ConfigMap
metadata:
  name: node-red-config
data:
  settings.js: |
    module.exports = {
      flowFile: 'flows.json',
      flowFilePretty: true,
      adminAuth: {
        type: "credentials",
        users: [{
          username: "admin",
          password: process.env.NODE_RED_ADMIN_PASSWORD,
          permissions: "*"
        }]
      },
      uiPort: process.env.PORT || 1880,
      diagnostics: {
        enabled: true,
        ui: true,
      },
      runtimeState: {
        enabled: false,
        ui: false,
      },
      logging: {
        console: {
          level: "info",
          metrics: false,
          audit: false
        }
      },
      exportGlobalContextKeys: false,
      editorTheme: {
        projects: {
          enabled: false,
          workflow: {
            mode: "manual"
          }
        },
        codeEditor: {
          lib: "monaco"
        }
      },
      functionExternalModules: true,
      functionGlobalContext: {
        bitvavo:require('bitvavo'),
      },
      debugMaxLength: 2500,
      mqttReconnectTime: 15000,
      serialReconnectTime: 15000,
      credentialSecret: process.env.NODE_RED_CREDENTIAL_SECRET,
    }
