apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
        - name: node-red
          image: isenne/nodered:latest
          volumeMounts:
            - name: node-red-storage
              mountPath: /data
            - name: node-red-config
              mountPath: /data/settings.js
              subPath: settings.js
          ports:
            - containerPort: 1880
          env:
            - name: TZ
              value: Europe/Amsterdam
            - name: CREDENTIAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: node-red-secret
                  key: NODE_RED_CREDENTIAL_SECRET
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: node-red-secret
                  key: NODE_RED_ADMIN_PASSWORD
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
      volumes:
        - name: node-red-config
          configMap:
            name: node-red-config
        - name: node-red-storage
          persistentVolumeClaim:
            claimName: node-red-lh-pvc
