apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
        - name: node-red
          image: isenne/nodered:latest
          imagePullPolicy: "Always"
          imagePullSecrets:
            - name: docker-hub-secret
          volumeMounts:
            - name: node-red-storage
              mountPath: /data
          ports:
            - containerPort: 1880
          env:
            - name: TZ
              value: Europe/Amsterdam
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
      volumes:
        - name: node-red-storage
          persistentVolumeClaim:
            claimName: node-red-lh-pvc
