FROM nodered/node-red

RUN npm install node-red-contrib-actionflows \
    node-red-contrib-chronos \
    node-red-contrib-ecovacs-deebot \
    node-red-contrib-home-assistant-websocket \
    node-red-contrib-loop \
    node-red-contrib-simple-crypto \
    node-red-contrib-sonos-plus \
    node-red-contrib-tado-client \
    node-red-contrib-zigbee2mqtt \
    node-red-dashboard \
    node-red-node-mysql