- id: "1616703279600"
  alias: "[SENSOR] Overloop verlichting aan"
  description: ""
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.overloop_beweging
      to: "on"
  condition: []
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.nacht
              state: "on"
          sequence:
            - service: script.overloop_verlichting_aan_nacht
              data: {}
      default:
        - service: script.overloop_verlichting_aan_overdag
          data: {}
  mode: single
- id: "1616703422962"
  alias: "[SENSOR] Overloop verlichting uit"
  description: ""
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.overloop_beweging
      to: "off"
  condition: []
  action:
    - type: turn_off
      device_id: 76ea834f9f02d6cdeedf54be50382002
      entity_id: light.overloop_lamp
      domain: light
  mode: single
- id: "1610115816490"
  alias: "[MODE] Nachtmodus uit"
  description: ""
  trigger:
    - platform: time
      at: 07:00
  condition: []
  action:
    - service: script.nachtmodus_uit
      data: {}
  mode: single
- id: "1610117098943"
  alias: "[NIGHT] Slaapkamer uit"
  description: Na 2 uur
  trigger:
    - platform: state
      entity_id: input_boolean.nacht
      to: "on"
      for: 02:00:00
  condition: []
  action:
    - type: turn_off
      device_id: 43c20fe9ddca265ce4c47e8663b2451e
      entity_id: switch.slaapkamer_tv_plug
      domain: switch
    - type: turn_off
      device_id: 98c12ed81e5e992ee379f362f938fa88
      entity_id: switch.slaapkamer_elektrische_deken_plug
      domain: switch
  mode: single
- id: "1615825323780"
  alias: "[TIME] Verlichting beneden aan met zonsondergang"
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: -00:15:00
    - type: illuminance
      platform: device
      device_id: 03e3e4f2a9a7a4d95cc28a1913a154b2
      entity_id: sensor.woonkamer_bewegingssensor_achter_illuminance_lux
      domain: sensor
      below: 25
      for:
        hours: 0
        minutes: 5
        seconds: 0
  condition: []
  action:
    - service: script.woonkamer_aan
      data: {}
    - service: light.turn_on
      data:
        brightness_pct: 25
      target:
        entity_id: light.eetkamer_lamp
  mode: single
