- id: "1616703279600"
  alias: "[SENSOR] Overloop verlichting aan"
  description: ""
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.overloop_beweging
      to: "on"
  condition: []
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.nacht
              state: "on"
          sequence:
            - service: script.overloop_verlichting_aan_nacht
              data: {}
      default:
        - service: script.overloop_verlichting_aan_overdag
          data: {}
  mode: single
- id: "1616703422962"
  alias: "[SENSOR] Overloop verlichting uit"
  description: ""
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.overloop_beweging
      to: "off"
  condition: []
  action:
    - type: turn_off
      device_id: 76ea834f9f02d6cdeedf54be50382002
      entity_id: light.overloop_lamp
      domain: light
  mode: single
