# Loads default set of integrations. Do not remove.
default_config:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  name: !secret street_address
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 3
  unit_system: metric
  currency: EUR
  country: NL
  external_url: !secret external_url
  internal_url: !secret internal_url
  time_zone: "Europe/Amsterdam"
  legacy_templates: false
  customize: !include customize.yaml

tts:
  - platform: google_translate

frontend:
  extra_module_url:
    - /local/plugins/lovelace-card-mod/card-mod.js
    - /local/plugins/lovelace-auto-entities/auto-entities.js
    - /local/plugins/lovelace-layout-card/layout-card.js
    - /local/plugins/lovelace-mushroom/mushroom.js
    - /local/plugins/mini-graph-card/mini-graph-card-bundle.js
    - /local/plugins/clock-weather-card/clock-weather-card.js

http:
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.0.0.0/8
    - 127.0.0.1
    - 10.244.0.0/16
    - ::1
    - 192.168.100.200/29

recorder:
  purge_keep_days: 5
  db_url: !secret recorder_db_url
  exclude:
    domains:
      - automation
      - updater
    entity_globs:
      - sensor.weather_*
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date
      - sensor.home_assistant_v2_db
    event_types:
      - call_service

logger:
  default: warning
  logs:
    homeassistant.components.mqtt.light.schema_json: error

device_tracker:
  - platform: tado
    username: !secret tado_email
    password: !secret tado_password
    home_id: !secret tado_home_id

sensor: !include sensors.yaml
light: !include lights.yaml
binary_sensor: !include binary_sensors.yaml
utility_meter: !include utility_meters.yaml
input_text: !include input_texts.yaml
input_boolean: !include input_booleans.yaml
input_number: !include input_numbers.yaml
template: !include templates.yaml
