sensor.gft:
  entity_picture: /local/images/gft.png
  friendly_name: Groente-, fruit- en tuinafval
sensor.restafval:
  entity_picture: /local/images/rest.png
  friendly_name: Restafval
sensor.papier:
  entity_picture: /local/images/papier.png
  friendly_name: Papier
sensor.pmd:
  entity_picture: /local/images/pmd.png
  friendly_name: Plastic, metalen en drinkpakken
sensor.energy_consumed_tariff_1:
  friendly_name: Stroom Dal
sensor.energy_consumed_tariff_2:
  friendly_name: Stroom Normaal
sensor.energy_produced_tariff_1:
  friendly_name: Teruglevering Dal
sensor.energy_produced_tariff_2:
  friendly_name: Teruglevering Normaal
sensor.gas_consumed:
  friendly_name: Gas
