stroom_normaal_tarief:
  name: Stroom normaal tarief
  icon: mdi:currency-eur
  min: 0
  max: 10
  step: 0.0001
  unit_of_measurement: EUR/kWh
  mode: box
stroom_dal_tarief:
  name: Stroom dal tarief
  icon: mdi:currency-eur
  min: 0
  max: 10
  step: 0.0001
  unit_of_measurement: EUR/kWh
  mode: box
gas_tarief:
  name: Gas tarief
  icon: mdi:currency-eur
  min: 0
  max: 10
  step: 0.0001
  unit_of_measurement: EUR/m³
  mode: box
terugleververgoeding:
  name: Terugleververgoeding
  icon: mdi:currency-eur
  min: 0
  max: 10
  step: 0.0001
  unit_of_measurement: EUR/kWh
  mode: box
