- id: "1672766380365"
  name: Woonkamer Normaal
  entities:
    light.keuken_aanrecht_lamp:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
        - color_temp
        - xy
      color_mode: xy
      brightness: 75
      hs_color:
        - 30
        - 43.137
      rgb_color:
        - 255
        - 200
        - 145
      xy_color:
        - 0.443
        - 0.379
      friendly_name: Keuken Aanrecht Lamp
      supported_features: 40
      state: "on"
    light.keuken_afzuigkap_lamp:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
        - color_temp
        - xy
      color_mode: xy
      brightness: 189
      hs_color:
        - 30.207
        - 56.863
      rgb_color:
        - 255
        - 183
        - 110
      xy_color:
        - 0.491
        - 0.39
      friendly_name: Keuken Afzuigkap Lamp
      supported_features: 40
      state: "on"
    light.woonkamer_lamp_1:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
        - blink
        - breathe
        - okay
        - channel_change
        - finish_effect
        - stop_effect
      supported_color_modes:
        - color_temp
        - xy
      friendly_name: Woonkamer Lamp 1
      supported_features: 44
      state: "off"
    light.woonkamer_lamp_2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
        - blink
        - breathe
        - okay
        - channel_change
        - finish_effect
        - stop_effect
      supported_color_modes:
        - color_temp
        - xy
      color_mode: xy
      brightness: 127
      hs_color:
        - 44.727
        - 43.137
      rgb_color:
        - 255
        - 227
        - 145
      xy_color:
        - 0.42
        - 0.411
      friendly_name: Woonkamer Lamp 2
      supported_features: 44
      state: "on"
    light.woonkamer_mooie_lamp:
      effect_list:
        - blink
        - breathe
        - okay
        - channel_change
        - finish_effect
        - stop_effect
      supported_color_modes:
        - brightness
      friendly_name: Woonkamer Mooie Lamp
      supported_features: 44
      color_mode: brightness
      brightness: 18
      state: "on"
    light.woonkamer_statief_lamp:
      min_color_temp_kelvin: 1801
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 555
      effect_list:
        - blink
        - breathe
        - okay
        - channel_change
        - finish_effect
        - stop_effect
      supported_color_modes:
        - color_temp
        - xy
      color_mode: xy
      brightness: 13
      hs_color:
        - 27.925
        - 62.353
      rgb_color:
        - 255
        - 170
        - 96
      xy_color:
        - 0.516
        - 0.386
      friendly_name: Woonkamer Statief Lamp
      supported_features: 44
      state: "on"
  icon: mdi:sofa
  metadata: {}
