# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/

street_address: Street name
postal_code: 1111XX
street_number: 1
latitude: 45.828710
longitude: 6.867310

external_url: https://external.url
internal_url: http://127.0.0.1:8123

samsung_device_id: some_id
samsung_mac: xx:xx:xx:xx:xx:xx
smart_things_api_token: token

recorder_db_url: mysql://mysql_usernam:mysql_password@server:port/database?charset=utf8mb4
