- platform: afvalbeheer
  updateinterval: 3
  wastecollector: ACV
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: !secret postal_code
  streetnumber: !secret street_number
  upcomingsensor: 1
  dateformat: "%d-%m-%Y"
  nameprefix: 0
