version: '3.8'

# Basic Home Assistant setup
services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=${TZ}
    volumes:
      - ./hassio/config:/config
    ports:
      - ${HA_PORT}:${HA_PORT}
