homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.100.201:30883
serial:
  port: /dev/ttyACM0
  disable_led: true
frontend:
  port: 8099
  url: https://z2m.punter3.nl
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_level: warn
device_options:
  legacy: false
devices: devices.yaml
groups: groups.yaml
