apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      imagePullSecrets:
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:latest
          imagePullPolicy: "Always"
          volumeMounts:
            - name: zigbee2mqtt-storage
              mountPath: /app/data
            - name: config-volume
              mountPath: /app/data/configmap.yaml
              subPath: configmap.yaml
            - name: usb-device
              mountPath: /dev/zigbee2mqtt
          ports:
            - containerPort: 8099
          env:
            - name: TZ
              value: Europe/Amsterdam
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
      volumes:
        - name: zigbee2mqtt-storage
          persistentVolumeClaim:
            claimName: zigbee2mqtt-pvc
        - name: config-volume
          configMap:
            name: zigbee2mqtt-config
        - name: usb-device
          hostPath:
            path: /dev/zigbee2mqtt
