apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt-service
spec:
  selector:
    app: zigbee2mqtt
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 8099
---
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt-nodeport
spec:
  type: NodePort
  selector:
    app: zigbee2mqtt
  ports:
    - protocol: TCP
      port: 8099
      nodePort: 30099
